#!/usr/bin/env sh

changed_files=$(git diff --cached --name-only --diff-filter=ACM)

if [ -z "$changed_files" ]; then
  echo "No staged files found. Skipping lint-staged."
  exit 0
fi

LINT_STAGED_EXTENSIONS="js|ts|vue|css|scss"

if echo "$changed_files" | grep -qE "\.($LINT_STAGED_EXTENSIONS)$"; then
  echo "Found files for lint-staged. Running checks..."
  npx lint-staged
else
  echo "No files for lint-staged found. Skipping checks."
  exit 0
fi
