services:
  frontend_public:
    build:
      context: frontend/public
      dockerfile: Dockerfile
    restart: 'always'
    ports:
      - '3000:3000'

  frontend_auth:
    build:
      context: frontend/auth
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
  
  frontend_code_editor:
    build:
      context: frontend/code_editor
      dockerfile: Dockerfile
    ports:
      - '3002:3000'

  frontend_onboarding:
    build:
      context: frontend/onboarding
      dockerfile: Dockerfile
    ports:
      - '3003:3000'

  frontend_profile:
    build:
      context: frontend/profile
      dockerfile: Dockerfile
    ports:
      - '3004:3000'

  frontend_roadmaps:
    build:
      context: frontend/roadmaps
      dockerfile: Dockerfile
    ports:
      - '3005:3000'
