services:
  frontend_public:
    build:
      context: frontend/public
      dockerfile: Dockerfile
    restart: 'always'
    ports:
      - '3000:3000'

  frontend_auth:
    build:
      context: frontend/auth
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
  
  frontend_code_editor:
    build:
      context: frontend/code_editor
      dockerfile: Dockerfile
    ports:
      - '3002:3000'

  frontend_onboarding:
    build:
      context: frontend/onboarding
      dockerfile: Dockerfile
    ports:
      - '3003:3000'

  frontend_profile:
    build:
      context: frontend/profile
      dockerfile: Dockerfile
    ports:
      - '3004:3000'

  frontend_roadmaps:
    build:
      context: frontend/roadmaps
      dockerfile: Dockerfile
    ports:
      - '3005:3000'

  backend_auth_service:
    build:
      context: backend/auth
      dockerfile: Dockerfile
    container_name: auth-service
    env_file:
      - .env.local
    environment:
      - POSTGRES_HOST=db
    ports:
      - "8001:8001"
    depends_on:
      - postgres

  backend_onboarding_service:
    build:
      context: backend/onboarding
      dockerfile: Dockerfile
    container_name: onboarding-service
    env_file:
      - .env.local
    environment:
      - POSTGRES_HOST=db
    ports:
      - "8002:8002"
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    container_name: db
    env_file:
      - .env
      - .env.local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    tty: true

volumes:
  postgres_data:
