import type { Course } from '../model/course';

export type Category = {
    id: string;
    title: string;
    challengesCount: number;
};

export type Language = {
    id: string;
    title: string;
    challengesCount: number;
};

const COURSES_FOR_TEST: Course[] = [
    {
        id: 'course_001',
        title: 'JavaScript для начинающих',
        status: 'hot',
        description:
            'Полный курс по основам JavaScript. Изучите переменные, функции, массивы, объекты и многое другое. Курс подходит для тех, кто никогда не программировал.',
        category: 'programming',
        subCategory: 'frontend',
        tags: ['javascript', 'frontend', 'web-development', 'beginner'],
        icon: '🎯',
        difficulty: 'beginner',
        xpReward: 500,
        estimatedHours: 3.5,
        userMeta: {
            startCourse: false,
        },
        modules: [
            {
                id: 'module_001_1',
                title: 'Введение в JavaScript',
                lessons: [
                    {
                        id: 'lesson_001_1_1',
                        title: 'Что такое JavaScript и как он работает',
                        slug: 'what-is-javascript',
                        description:
                            'История создания, особенности языка, запуск в браузере и Node.js',
                        status: 'not-passed',
                        tags: ['intro', 'history', 'basics'],
                        difficulty: 'easy',
                        durationInMinutes: 25,
                        xpReward: 50,
                        mdContent:
                            '# Что такое JavaScript\n\nJavaScript - это язык программирования...',
                        tasks: [
                            {
                                id: 'task_001_1_1_1',
                                variants: [
                                    { id: 'var1', title: 'Python', isAnswer: false },
                                    { id: 'var2', title: 'JavaScript', isAnswer: true },
                                    { id: 'var3', title: 'Java', isAnswer: false },
                                ],
                            },
                        ],
                    },
                    {
                        id: 'lesson_001_1_2',
                        title: 'Переменные и типы данных',
                        slug: 'variables-and-data-types',
                        description:
                            'var, let, const, строки, числа, булевы значения, null, undefined',
                        status: 'not-passed',
                        tags: ['variables', 'data-types', 'basics'],
                        difficulty: 'easy',
                        durationInMinutes: 35,
                        xpReward: 70,
                        mdContent:
                            '# Переменные в JavaScript\n\nДля объявления переменных используются...',
                        tasks: [
                            {
                                id: 'task_001_1_2_1',
                                variants: [
                                    { id: 'var1', title: 'const', isAnswer: true },
                                    { id: 'var2', title: 'variable', isAnswer: false },
                                ],
                            },
                        ],
                    },
                    {
                        id: 'lesson_001_1_3',
                        title: 'Условные операторы',
                        slug: 'conditional-operators',
                        description: 'if, else, else if, switch, тернарный оператор',
                        status: 'not-passed',
                        tags: ['conditions', 'if-else', 'switch'],
                        difficulty: 'easy',
                        durationInMinutes: 30,
                        xpReward: 60,
                        mdContent:
                            '# Условные операторы\n\nУсловные операторы позволяют выполнять...',
                        tasks: [],
                    },
                ],
            },
            {
                id: 'module_001_2',
                title: 'Функции и массивы',
                lessons: [
                    {
                        id: 'lesson_001_2_1',
                        title: 'Функции: объявление и вызов',
                        slug: 'functions-basics',
                        description:
                            'Function declaration, function expression, стрелочные функции',
                        status: 'not-passed',
                        tags: ['functions', 'basics'],
                        difficulty: 'easy',
                        durationInMinutes: 40,
                        xpReward: 80,
                        mdContent:
                            '# Функции\n\nФункции - это блоки кода, которые можно вызывать...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_001_2_2',
                        title: 'Массивы и методы работы с ними',
                        slug: 'arrays',
                        description: 'Создание массивов, push, pop, map, filter, reduce',
                        status: 'not-passed',
                        tags: ['arrays', 'methods'],
                        difficulty: 'medium',
                        durationInMinutes: 45,
                        xpReward: 90,
                        mdContent:
                            '# Массивы\n\nМассивы используются для хранения упорядоченных коллекций...',
                        tasks: [
                            {
                                id: 'task_001_2_2_1',
                                variants: [
                                    { id: 'var1', title: 'map()', isAnswer: true },
                                    { id: 'var2', title: 'forEach()', isAnswer: false },
                                ],
                            },
                        ],
                    },
                    {
                        id: 'lesson_001_2_3',
                        title: 'Объекты и их свойства',
                        slug: 'objects',
                        description: 'Создание объектов, доступ к свойствам, методы объектов',
                        status: 'not-passed',
                        tags: ['objects', 'properties'],
                        difficulty: 'medium',
                        durationInMinutes: 35,
                        xpReward: 70,
                        mdContent: '# Объекты\n\nОбъекты - это коллекции свойств...',
                        tasks: [],
                    },
                ],
            },
            {
                id: 'module_001_3',
                title: 'Продвинутые темы',
                lessons: [
                    {
                        id: 'lesson_001_3_1',
                        title: 'Замыкания и область видимости',
                        slug: 'closures-and-scope',
                        description: 'Глобальная, локальная и блочная область видимости, замыкания',
                        status: 'not-passed',
                        tags: ['closures', 'scope'],
                        difficulty: 'hard',
                        durationInMinutes: 50,
                        xpReward: 100,
                        mdContent: '# Замыкания\n\nЗамыкание - это функция, которая запоминает...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_001_3_2',
                        title: 'Асинхронность: Promise и async/await',
                        slug: 'async-promises',
                        description: 'Колбэки, промисы, async/await, обработка ошибок',
                        status: 'not-passed',
                        tags: ['async', 'promises', 'await'],
                        difficulty: 'hard',
                        durationInMinutes: 55,
                        xpReward: 110,
                        mdContent:
                            '# Асинхронный JavaScript\n\nАсинхронность позволяет выполнять...',
                        tasks: [
                            {
                                id: 'task_001_3_2_1',
                                variants: [
                                    { id: 'var1', title: '.then()', isAnswer: false },
                                    { id: 'var2', title: 'await', isAnswer: true },
                                ],
                            },
                        ],
                    },
                ],
            },
        ],
    },
    {
        id: 'course_002',
        title: 'TypeScript: Полное руководство',
        status: null,
        description:
            'Изучите TypeScript с нуля до продвинутого уровня. Типизация, интерфейсы, generics, утилитарные типы и интеграция с React.',
        category: 'programming',
        subCategory: 'frontend',
        tags: ['typescript', 'javascript', 'frontend', 'hard'],
        icon: '📘',
        difficulty: 'intermediate',
        xpReward: 800,
        estimatedHours: 2.5,
        userMeta: {
            startCourse: true,
            currentLesson: 1,
            currentModule: 2,
        },
        modules: [
            {
                id: 'module_002_1',
                title: 'Основы TypeScript',
                lessons: [
                    {
                        id: 'lesson_002_1_1',
                        title: 'Введение в TypeScript',
                        slug: 'intro-to-typescript',
                        description: 'Что такое TypeScript, установка, настройка tsconfig.json',
                        status: 'active',
                        tags: ['intro', 'setup'],
                        difficulty: 'easy',
                        durationInMinutes: 30,
                        xpReward: 60,
                        mdContent: '# TypeScript\n\nTypeScript - это надмножество JavaScript...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_002_1_2',
                        title: 'Базовые типы',
                        slug: 'basic-types',
                        description: 'string, number, boolean, array, tuple, enum',
                        status: 'not-passed',
                        tags: ['types', 'basics'],
                        difficulty: 'easy',
                        durationInMinutes: 35,
                        xpReward: 70,
                        mdContent:
                            '# Базовые типы\n\nTypeScript предоставляет богатую систему типов...',
                        tasks: [
                            {
                                id: 'task_002_1_2_1',
                                variants: [
                                    { id: 'var1', title: 'tuple', isAnswer: true },
                                    { id: 'var2', title: 'object', isAnswer: false },
                                ],
                            },
                        ],
                    },
                    {
                        id: 'lesson_002_1_3',
                        title: 'Union и Intersection типы',
                        slug: 'union-intersection',
                        description: 'Объединение и пересечение типов, type aliases',
                        status: 'not-passed',
                        tags: ['union', 'intersection'],
                        difficulty: 'medium',
                        durationInMinutes: 40,
                        xpReward: 80,
                        mdContent: '# Union и Intersection\n\nUnion типы позволяют переменной...',
                        tasks: [],
                    },
                ],
            },
            {
                id: 'module_002_2',
                title: 'Продвинутая типизация',
                lessons: [
                    {
                        id: 'lesson_002_2_1',
                        title: 'Интерфейсы',
                        slug: 'interfaces',
                        description: 'Создание интерфейсов, опциональные свойства, readonly',
                        status: 'not-passed',
                        tags: ['interfaces'],
                        difficulty: 'medium',
                        durationInMinutes: 35,
                        xpReward: 70,
                        mdContent: '# Интерфейсы\n\nИнтерфейсы описывают форму объекта...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_002_2_2',
                        title: 'Generics',
                        slug: 'generics',
                        description: 'Обобщенные типы, ограничения, generic функции и классы',
                        status: 'not-passed',
                        tags: ['generics'],
                        difficulty: 'hard',
                        durationInMinutes: 50,
                        xpReward: 100,
                        mdContent: '# Generics\n\nGenerics позволяют создавать компоненты...',
                        tasks: [
                            {
                                id: 'task_002_2_2_1',
                                variants: [
                                    { id: 'var1', title: '<T>', isAnswer: true },
                                    { id: 'var2', title: 'any', isAnswer: false },
                                ],
                            },
                        ],
                    },
                    {
                        id: 'lesson_002_2_3',
                        title: 'Утилитарные типы',
                        slug: 'utility-types',
                        description: 'Partial, Required, Readonly, Pick, Omit, Record',
                        status: 'not-passed',
                        tags: ['utility-types'],
                        difficulty: 'hard',
                        durationInMinutes: 45,
                        xpReward: 90,
                        mdContent: '# Утилитарные типы\n\nTypeScript предоставляет встроенные...',
                        tasks: [],
                    },
                ],
            },
            {
                id: 'module_002_3',
                title: 'TypeScript в React',
                lessons: [
                    {
                        id: 'lesson_002_3_1',
                        title: 'Типизация компонентов React',
                        slug: 'react-components-typing',
                        description: 'FC, PropsWithChildren, типизация пропсов',
                        status: 'not-passed',
                        tags: ['react', 'components'],
                        difficulty: 'hard',
                        durationInMinutes: 40,
                        xpReward: 80,
                        mdContent: '# React + TypeScript\n\nТипизация React компонентов...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_002_3_2',
                        title: 'Хуки с TypeScript',
                        slug: 'hooks-with-typescript',
                        description: 'useState, useEffect, useReducer, useContext с типами',
                        status: 'not-passed',
                        tags: ['hooks', 'react'],
                        difficulty: 'hard',
                        durationInMinutes: 45,
                        xpReward: 90,
                        mdContent: '# Типизация хуков\n\nКаждый React хук можно типизировать...',
                        tasks: [
                            {
                                id: 'task_002_3_2_1',
                                variants: [
                                    { id: 'var1', title: 'useState<number>', isAnswer: true },
                                    { id: 'var2', title: 'useState()', isAnswer: false },
                                ],
                            },
                        ],
                    },
                ],
            },
        ],
    },
    {
        id: 'course_003',
        title: 'React с нуля до профи',
        status: 'popular',
        description:
            'Освойте React 18+ полностью: компоненты, хуки, управление состоянием, маршрутизация, работа с API и оптимизация производительности.',
        category: 'programming',
        subCategory: 'frontend',
        tags: ['react', 'javascript', 'frontend', 'hooks', 'redux'],
        icon: '⚛️',
        difficulty: 'intermediate',
        xpReward: 1200,
        estimatedHours: 4.5,
        userMeta: {
            startCourse: false,
        },
        modules: [
            {
                id: 'module_003_1',
                title: 'Введение в React',
                lessons: [
                    {
                        id: 'lesson_003_1_1',
                        title: 'Создание React-приложения',
                        slug: 'create-react-app',
                        description: 'Vite, CRA, структура проекта',
                        status: 'not-passed',
                        tags: ['setup', 'vite'],
                        difficulty: 'easy',
                        durationInMinutes: 25,
                        xpReward: 50,
                        mdContent:
                            '# Создание React приложения\n\nИспользуйте Vite для быстрого старта...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_003_1_2',
                        title: 'Компоненты и JSX',
                        slug: 'components-and-jsx',
                        description: 'Функциональные компоненты, JSX синтаксис, вставка выражений',
                        status: 'not-passed',
                        tags: ['jsx', 'components'],
                        difficulty: 'easy',
                        durationInMinutes: 35,
                        xpReward: 70,
                        mdContent: '# JSX\n\nJSX - это синтаксическое расширение JavaScript...',
                        tasks: [
                            {
                                id: 'task_003_1_2_1',
                                variants: [
                                    { id: 'var1', title: 'className', isAnswer: true },
                                    { id: 'var2', title: 'class', isAnswer: false },
                                ],
                            },
                        ],
                    },
                    {
                        id: 'lesson_003_1_3',
                        title: 'Props и состояния',
                        slug: 'props-and-state',
                        description: 'Передача данных через props, useState, подъем состояния',
                        status: 'not-passed',
                        tags: ['props', 'state'],
                        difficulty: 'medium',
                        durationInMinutes: 40,
                        xpReward: 80,
                        mdContent: '# Props и State\n\nProps передаются от родителя к ребенку...',
                        tasks: [],
                    },
                ],
            },
            {
                id: 'module_003_2',
                title: 'Хуки и эффекты',
                lessons: [
                    {
                        id: 'lesson_003_2_1',
                        title: 'useEffect и жизненный цикл',
                        slug: 'useeffect',
                        description: 'Побочные эффекты, монтирование, обновление, размонтирование',
                        status: 'not-passed',
                        tags: ['useeffect', 'lifecycle'],
                        difficulty: 'medium',
                        durationInMinutes: 45,
                        xpReward: 90,
                        mdContent:
                            '# useEffect\n\nuseEffect позволяет выполнять побочные эффекты...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_003_2_2',
                        title: 'useContext для глобального состояния',
                        slug: 'usecontext',
                        description: 'Создание контекста, провайдер, потребитель',
                        status: 'not-passed',
                        tags: ['context', 'state-management'],
                        difficulty: 'medium',
                        durationInMinutes: 35,
                        xpReward: 70,
                        mdContent:
                            '# useContext\n\nКонтекст позволяет передавать данные глубоко...',
                        tasks: [
                            {
                                id: 'task_003_2_2_1',
                                variants: [
                                    { id: 'var1', title: 'createContext()', isAnswer: true },
                                    { id: 'var2', title: 'new Context()', isAnswer: false },
                                ],
                            },
                        ],
                    },
                    {
                        id: 'lesson_003_2_3',
                        title: 'useReducer для сложной логики',
                        slug: 'usereducer',
                        description: 'Альтернатива useState, паттерн редьюсер',
                        status: 'not-passed',
                        tags: ['usereducer'],
                        difficulty: 'hard',
                        durationInMinutes: 40,
                        xpReward: 80,
                        mdContent:
                            '# useReducer\n\nuseReducer подходит для управления сложным состоянием...',
                        tasks: [],
                    },
                ],
            },
            {
                id: 'module_003_3',
                title: 'Маршрутизация и API',
                lessons: [
                    {
                        id: 'lesson_003_3_1',
                        title: 'React Router v6',
                        slug: 'react-router',
                        description: 'BrowserRouter, Routes, Route, Link, useParams',
                        status: 'not-passed',
                        tags: ['routing', 'react-router'],
                        difficulty: 'medium',
                        durationInMinutes: 50,
                        xpReward: 100,
                        mdContent: '# React Router\n\nReact Router позволяет создавать...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_003_3_2',
                        title: 'Работа с API: fetch и axios',
                        slug: 'api-fetch-axios',
                        description: 'GET, POST, PUT, DELETE запросы, обработка ошибок',
                        status: 'not-passed',
                        tags: ['api', 'fetch', 'axios'],
                        difficulty: 'hard',
                        durationInMinutes: 45,
                        xpReward: 90,
                        mdContent:
                            '# Работа с API\n\nДля запросов к серверу используются fetch или axios...',
                        tasks: [
                            {
                                id: 'task_003_3_2_1',
                                variants: [
                                    { id: 'var1', title: 'fetch()', isAnswer: true },
                                    { id: 'var2', title: 'get()', isAnswer: false },
                                ],
                            },
                        ],
                    },
                ],
            },
            {
                id: 'module_003_4',
                title: 'Управление состоянием (Redux)',
                lessons: [
                    {
                        id: 'lesson_003_4_1',
                        title: 'Redux Toolkit',
                        slug: 'redux-toolkit',
                        description: 'createSlice, configureStore, useSelector, useDispatch',
                        status: 'not-passed',
                        tags: ['redux', 'redux-toolkit'],
                        difficulty: 'hard',
                        durationInMinutes: 55,
                        xpReward: 110,
                        mdContent:
                            '# Redux Toolkit\n\nRedux Toolkit - официальный инструментарий...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_003_4_2',
                        title: 'Асинхронные действия (createAsyncThunk)',
                        slug: 'async-thunk',
                        description: 'Асинхронные запросы в Redux, extraReducers',
                        status: 'not-passed',
                        tags: ['async', 'thunk'],
                        difficulty: 'hard',
                        durationInMinutes: 50,
                        xpReward: 100,
                        mdContent: '# Асинхронные действия\n\ncreateAsyncThunk упрощает работу...',
                        tasks: [],
                    },
                ],
            },
        ],
    },
    {
        id: 'course_004',
        title: 'Node.js и Express',
        status: 'new',
        description:
            'Создание серверных приложений на Node.js. Изучите Express, middleware, маршрутизацию, работу с базами данных и аутентификацию.',
        category: 'programming',
        subCategory: 'backend',
        tags: ['nodejs', 'express', 'backend', 'javascript', 'api'],
        icon: '🚀',
        difficulty: 'hard',
        xpReward: 1000,
        estimatedHours: 3.5,
        userMeta: {
            startCourse: true,
            currentLesson: 2,
        },
        modules: [
            {
                id: 'module_004_1',
                title: 'Введение в Node.js',
                lessons: [
                    {
                        id: 'lesson_004_1_1',
                        title: 'Установка и основы Node.js',
                        slug: 'nodejs-setup',
                        description: 'Установка Node.js, npm, первый скрипт',
                        status: 'active',
                        tags: ['setup', 'npm'],
                        difficulty: 'easy',
                        durationInMinutes: 25,
                        xpReward: 50,
                        mdContent:
                            '# Node.js\n\nNode.js - среда выполнения JavaScript на сервере...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_004_1_2',
                        title: 'Модули CommonJS и ES',
                        slug: 'modules-cjs-esm',
                        description: 'require, import, exports, module.exports',
                        status: 'not-passed',
                        tags: ['modules'],
                        difficulty: 'easy',
                        durationInMinutes: 30,
                        xpReward: 60,
                        mdContent: '# Модули\n\nNode.js поддерживает CommonJS и ES модули...',
                        tasks: [
                            {
                                id: 'task_004_1_2_1',
                                variants: [
                                    { id: 'var1', title: 'require()', isAnswer: true },
                                    { id: 'var2', title: 'include()', isAnswer: false },
                                ],
                            },
                        ],
                    },
                    {
                        id: 'lesson_004_1_3',
                        title: 'Встроенные модули: fs, path, os',
                        slug: 'built-in-modules',
                        description: 'Работа с файлами, путями, операционной системой',
                        status: 'not-passed',
                        tags: ['fs', 'path', 'os'],
                        difficulty: 'medium',
                        durationInMinutes: 35,
                        xpReward: 70,
                        mdContent: '# Встроенные модули\n\nNode.js предоставляет множество...',
                        tasks: [],
                    },
                ],
            },
            {
                id: 'module_004_2',
                title: 'Express.js',
                lessons: [
                    {
                        id: 'lesson_004_2_1',
                        title: 'Создание сервера на Express',
                        slug: 'express-server',
                        description: 'Установка Express, маршруты, app.get, app.post',
                        status: 'not-passed',
                        tags: ['express', 'server'],
                        difficulty: 'medium',
                        durationInMinutes: 40,
                        xpReward: 80,
                        mdContent: '# Express\n\nExpress - минималистичный веб-фреймворк...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_004_2_2',
                        title: 'Middleware в Express',
                        slug: 'express-middleware',
                        description: 'Встроенные middleware, сторонние, создание своих',
                        status: 'not-passed',
                        tags: ['middleware'],
                        difficulty: 'medium',
                        durationInMinutes: 45,
                        xpReward: 90,
                        mdContent: '# Middleware\n\nMiddleware - функции, которые имеют доступ...',
                        tasks: [
                            {
                                id: 'task_004_2_2_1',
                                variants: [
                                    { id: 'var1', title: 'app.use()', isAnswer: true },
                                    { id: 'var2', title: 'app.middleware()', isAnswer: false },
                                ],
                            },
                        ],
                    },
                    {
                        id: 'lesson_004_2_3',
                        title: 'Обработка ошибок',
                        slug: 'error-handling',
                        description: 'try/catch, error-handling middleware',
                        status: 'not-passed',
                        tags: ['errors'],
                        difficulty: 'hard',
                        durationInMinutes: 35,
                        xpReward: 70,
                        mdContent: '# Обработка ошибок\n\nВ Express есть специальный middleware...',
                        tasks: [],
                    },
                ],
            },
            {
                id: 'module_004_3',
                title: 'Базы данных и аутентификация',
                lessons: [
                    {
                        id: 'lesson_004_3_1',
                        title: 'MongoDB и Mongoose',
                        slug: 'mongodb-mongoose',
                        description: 'Подключение, схемы, модели, CRUD операции',
                        status: 'not-passed',
                        tags: ['mongodb', 'mongoose'],
                        difficulty: 'hard',
                        durationInMinutes: 55,
                        xpReward: 110,
                        mdContent: '# MongoDB\n\nMongoDB - NoSQL база данных...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_004_3_2',
                        title: 'JWT аутентификация',
                        slug: 'jwt-auth',
                        description: 'Регистрация, логин, защита маршрутов, bcrypt',
                        status: 'not-passed',
                        tags: ['jwt', 'auth'],
                        difficulty: 'hard',
                        durationInMinutes: 60,
                        xpReward: 120,
                        mdContent: '# JWT\n\nJSON Web Tokens для аутентификации...',
                        tasks: [
                            {
                                id: 'task_004_3_2_1',
                                variants: [
                                    { id: 'var1', title: 'jwt.sign()', isAnswer: true },
                                    { id: 'var2', title: 'jwt.create()', isAnswer: false },
                                ],
                            },
                        ],
                    },
                ],
            },
        ],
    },
    {
        id: 'course_005',
        title: 'Python для анализа данных',
        status: null,
        description:
            'Изучите Python для работы с данными. Pandas, NumPy, Matplotlib, основы статистики и визуализации данных.',
        category: 'data-science',
        subCategory: 'data-analysis',
        tags: ['python', 'data-science', 'pandas', 'numpy', 'matplotlib'],
        icon: '🐍',
        difficulty: 'beginner',
        xpReward: 600,
        estimatedHours: 2.5,
        userMeta: {
            startCourse: false,
        },
        modules: [
            {
                id: 'module_005_1',
                title: 'Основы Python',
                lessons: [
                    {
                        id: 'lesson_005_1_1',
                        title: 'Синтаксис и типы данных',
                        slug: 'python-syntax',
                        description: 'Переменные, строки, числа, списки, словари',
                        status: 'not-passed',
                        tags: ['syntax', 'basics'],
                        difficulty: 'easy',
                        durationInMinutes: 40,
                        xpReward: 80,
                        mdContent: '# Python\n\nPython - интерпретируемый язык...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_005_1_2',
                        title: 'Циклы и условия',
                        slug: 'loops-conditions',
                        description: 'if, for, while, range',
                        status: 'not-passed',
                        tags: ['loops', 'conditions'],
                        difficulty: 'easy',
                        durationInMinutes: 30,
                        xpReward: 60,
                        mdContent: '# Циклы\n\nЦиклы позволяют повторять код...',
                        tasks: [
                            {
                                id: 'task_005_1_2_1',
                                variants: [
                                    { id: 'var1', title: 'for i in range()', isAnswer: true },
                                    { id: 'var2', title: 'foreach', isAnswer: false },
                                ],
                            },
                        ],
                    },
                    {
                        id: 'lesson_005_1_3',
                        title: 'Функции и модули',
                        slug: 'functions-modules',
                        description: 'def, return, импорт модулей',
                        status: 'not-passed',
                        tags: ['functions'],
                        difficulty: 'medium',
                        durationInMinutes: 35,
                        xpReward: 70,
                        mdContent: '# Функции\n\nФункции группируют код...',
                        tasks: [],
                    },
                ],
            },
            {
                id: 'module_005_2',
                title: 'NumPy и Pandas',
                lessons: [
                    {
                        id: 'lesson_005_2_1',
                        title: 'NumPy: массивы и операции',
                        slug: 'numpy-arrays',
                        description: 'ndarray, векторизованные операции, broadcasting',
                        status: 'not-passed',
                        tags: ['numpy'],
                        difficulty: 'medium',
                        durationInMinutes: 45,
                        xpReward: 90,
                        mdContent: '# NumPy\n\nNumPy - библиотека для численных вычислений...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_005_2_2',
                        title: 'Pandas: DataFrame и Series',
                        slug: 'pandas-dataframe',
                        description: 'Чтение данных, фильтрация, группировка, merge',
                        status: 'not-passed',
                        tags: ['pandas'],
                        difficulty: 'hard',
                        durationInMinutes: 55,
                        xpReward: 110,
                        mdContent: '# Pandas\n\nPandas - библиотека для работы с данными...',
                        tasks: [
                            {
                                id: 'task_005_2_2_1',
                                variants: [
                                    { id: 'var1', title: 'pd.DataFrame()', isAnswer: true },
                                    { id: 'var2', title: 'pd.Table()', isAnswer: false },
                                ],
                            },
                        ],
                    },
                    {
                        id: 'lesson_005_2_3',
                        title: 'Очистка данных',
                        slug: 'data-cleaning',
                        description: 'Обработка пропусков, дубликатов, выбросов',
                        status: 'not-passed',
                        tags: ['cleaning'],
                        difficulty: 'hard',
                        durationInMinutes: 40,
                        xpReward: 80,
                        mdContent: '# Очистка данных\n\nРеальные данные требуют очистки...',
                        tasks: [],
                    },
                ],
            },
            {
                id: 'module_005_3',
                title: 'Визуализация',
                lessons: [
                    {
                        id: 'lesson_005_3_1',
                        title: 'Matplotlib основы',
                        slug: 'matplotlib',
                        description: 'Линейные графики, гистограммы, scatter plots',
                        status: 'not-passed',
                        tags: ['matplotlib', 'visualization'],
                        difficulty: 'medium',
                        durationInMinutes: 35,
                        xpReward: 70,
                        mdContent:
                            '# Matplotlib\n\nMatplotlib для создания статических графиков...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_005_3_2',
                        title: 'Seaborn: статистические графики',
                        slug: 'seaborn',
                        description: 'Тепловые карты, box plots, pair plots',
                        status: 'not-passed',
                        tags: ['seaborn'],
                        difficulty: 'medium',
                        durationInMinutes: 35,
                        xpReward: 70,
                        mdContent: '# Seaborn\n\nSeaborn построен на Matplotlib...',
                        tasks: [],
                    },
                ],
            },
        ],
    },
    {
        id: 'course_006',
        title: 'Vue.js: Быстрый старт',
        status: null,
        description:
            'Изучите Vue.js 3 с нуля. Composition API, компоненты, маршрутизация, управление состоянием с Pinia.',
        category: 'programming',
        subCategory: 'frontend',
        tags: ['vuejs', 'javascript', 'frontend', 'pinia'],
        icon: '🖖',
        difficulty: 'beginner',
        xpReward: 550,
        estimatedHours: 2.5,
        userMeta: {
            startCourse: true,
            currentLesson: 1,
        },
        modules: [
            {
                id: 'module_006_1',
                title: 'Основы Vue',
                lessons: [
                    {
                        id: 'lesson_006_1_1',
                        title: 'Создание Vue приложения',
                        slug: 'vue-setup',
                        description: 'Vue CLI, Vite, структура проекта',
                        status: 'active',
                        tags: ['setup'],
                        difficulty: 'easy',
                        durationInMinutes: 25,
                        xpReward: 50,
                        mdContent: '# Vue.js\n\nVue - прогрессивный фреймворк...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_006_1_2',
                        title: 'Директивы и шаблоны',
                        slug: 'directives-templates',
                        description: 'v-bind, v-if, v-for, v-on',
                        status: 'not-passed',
                        tags: ['directives'],
                        difficulty: 'easy',
                        durationInMinutes: 35,
                        xpReward: 70,
                        mdContent: '# Директивы\n\nДирективы - специальные атрибуты...',
                        tasks: [
                            {
                                id: 'task_006_1_2_1',
                                variants: [
                                    { id: 'var1', title: 'v-bind', isAnswer: true },
                                    { id: 'var2', title: 'v-model', isAnswer: false },
                                ],
                            },
                        ],
                    },
                    {
                        id: 'lesson_006_1_3',
                        title: 'Composition API',
                        slug: 'composition-api',
                        description: 'ref, reactive, setup script',
                        status: 'not-passed',
                        tags: ['composition-api'],
                        difficulty: 'medium',
                        durationInMinutes: 40,
                        xpReward: 80,
                        mdContent: '# Composition API\n\nComposition API - новый подход...',
                        tasks: [],
                    },
                ],
            },
            {
                id: 'module_006_2',
                title: 'Компоненты и маршрутизация',
                lessons: [
                    {
                        id: 'lesson_006_2_1',
                        title: 'Пропсы и события',
                        slug: 'props-emits',
                        description: 'defineProps, defineEmits',
                        status: 'not-passed',
                        tags: ['props', 'emits'],
                        difficulty: 'medium',
                        durationInMinutes: 35,
                        xpReward: 70,
                        mdContent: '# Пропсы\n\nКомпоненты общаются через props...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_006_2_2',
                        title: 'Vue Router',
                        slug: 'vue-router',
                        description: 'Настройка маршрутов, переходы, динамические пути',
                        status: 'not-passed',
                        tags: ['router'],
                        difficulty: 'medium',
                        durationInMinutes: 45,
                        xpReward: 90,
                        mdContent: '# Vue Router\n\nОфициальный роутер для Vue...',
                        tasks: [
                            {
                                id: 'task_006_2_2_1',
                                variants: [
                                    { id: 'var1', title: 'useRoute()', isAnswer: true },
                                    { id: 'var2', title: 'useRouter()', isAnswer: false },
                                ],
                            },
                        ],
                    },
                    {
                        id: 'lesson_006_2_3',
                        title: 'Жизненный цикл компонента',
                        slug: 'lifecycle-hooks',
                        description: 'onMounted, onUpdated, onUnmounted',
                        status: 'not-passed',
                        tags: ['lifecycle'],
                        difficulty: 'medium',
                        durationInMinutes: 30,
                        xpReward: 60,
                        mdContent: '# Хуки жизненного цикла\n\nVue предоставляет хуки...',
                        tasks: [],
                    },
                ],
            },
            {
                id: 'module_006_3',
                title: 'Управление состоянием',
                lessons: [
                    {
                        id: 'lesson_006_3_1',
                        title: 'Pinia: Основы',
                        slug: 'pinia-basics',
                        description: 'defineStore, state, getters, actions',
                        status: 'not-passed',
                        tags: ['pinia'],
                        difficulty: 'hard',
                        durationInMinutes: 45,
                        xpReward: 90,
                        mdContent: '# Pinia\n\nPinia - хранилище состояния для Vue...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_006_3_2',
                        title: 'Pinia: Практика',
                        slug: 'pinia-practice',
                        description: 'Асинхронные действия, сохранение состояния',
                        status: 'not-passed',
                        tags: ['pinia', 'async'],
                        difficulty: 'hard',
                        durationInMinutes: 40,
                        xpReward: 80,
                        mdContent: '# Асинхронные actions\n\nВ actions можно вызывать API...',
                        tasks: [],
                    },
                ],
            },
        ],
    },
    {
        id: 'course_007',
        title: 'Алгоритмы и структуры данных',
        status: 'new',
        description:
            'Глубокое погружение в алгоритмы и структуры данных. Подготовка к собеседованиям в топовые IT-компании.',
        category: 'computer-science',
        subCategory: 'algorithms',
        tags: ['algorithms', 'data-structures', 'interview-prep', 'leetcode'],
        icon: '🧮',
        difficulty: 'hard',
        xpReward: 1500,
        estimatedHours: 5.5,
        userMeta: {
            startCourse: false,
        },
        modules: [
            {
                id: 'module_007_1',
                title: 'Базовые структуры данных',
                lessons: [
                    {
                        id: 'lesson_007_1_1',
                        title: 'Массивы и строки',
                        slug: 'arrays-strings',
                        description: 'Операции, двумерные массивы, разворот строк',
                        status: 'not-passed',
                        tags: ['arrays', 'strings'],
                        difficulty: 'easy',
                        durationInMinutes: 40,
                        xpReward: 80,
                        mdContent: '# Массивы\n\nМассивы - фундаментальная структура...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_007_1_2',
                        title: 'Связные списки',
                        slug: 'linked-lists',
                        description: 'Односвязные, двусвязные, операции',
                        status: 'not-passed',
                        tags: ['linked-lists'],
                        difficulty: 'medium',
                        durationInMinutes: 50,
                        xpReward: 100,
                        mdContent:
                            '# Связные списки\n\nСвязный список - последовательность узлов...',
                        tasks: [
                            {
                                id: 'task_007_1_2_1',
                                variants: [
                                    {
                                        id: 'var1',
                                        title: 'O(1) для вставки в начало',
                                        isAnswer: true,
                                    },
                                    {
                                        id: 'var2',
                                        title: 'O(n) для вставки в начало',
                                        isAnswer: false,
                                    },
                                ],
                            },
                        ],
                    },
                    {
                        id: 'lesson_007_1_3',
                        title: 'Стек и очередь',
                        slug: 'stack-queue',
                        description: 'LIFO, FIFO, реализации',
                        status: 'not-passed',
                        tags: ['stack', 'queue'],
                        difficulty: 'medium',
                        durationInMinutes: 35,
                        xpReward: 70,
                        mdContent: '# Стек и очередь\n\nСтек - LIFO, очередь - FIFO...',
                        tasks: [],
                    },
                ],
            },
            {
                id: 'module_007_2',
                title: 'Продвинутые структуры',
                lessons: [
                    {
                        id: 'lesson_007_2_1',
                        title: 'Хеш-таблицы',
                        slug: 'hash-tables',
                        description: 'Хеш-функции, коллизии, разрешение',
                        status: 'not-passed',
                        tags: ['hash-table'],
                        difficulty: 'hard',
                        durationInMinutes: 45,
                        xpReward: 90,
                        mdContent: '# Хеш-таблицы\n\nХеш-таблица - ассоциативный массив...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_007_2_2',
                        title: 'Деревья и бинарный поиск',
                        slug: 'trees-bst',
                        description: 'Бинарные деревья, BST, обходы',
                        status: 'not-passed',
                        tags: ['trees', 'bst'],
                        difficulty: 'hard',
                        durationInMinutes: 55,
                        xpReward: 110,
                        mdContent: '# Деревья\n\nДерево - иерархическая структура...',
                        tasks: [
                            {
                                id: 'task_007_2_2_1',
                                variants: [
                                    { id: 'var1', title: 'in-order', isAnswer: true },
                                    { id: 'var2', title: 'random', isAnswer: false },
                                ],
                            },
                        ],
                    },
                    {
                        id: 'lesson_007_2_3',
                        title: 'Графы и BFS/DFS',
                        slug: 'graphs-bfs-dfs',
                        description: 'Представление графов, поиск в ширину и глубину',
                        status: 'not-passed',
                        tags: ['graphs', 'bfs', 'dfs'],
                        difficulty: 'hard',
                        durationInMinutes: 60,
                        xpReward: 120,
                        mdContent: '# Графы\n\nГрафы - вершины и ребра...',
                        tasks: [],
                    },
                ],
            },
            {
                id: 'module_007_3',
                title: 'Алгоритмы сортировки и поиска',
                lessons: [
                    {
                        id: 'lesson_007_3_1',
                        title: 'Сортировка пузырьком и быстрая',
                        slug: 'sorting-bubble-quick',
                        description: 'O(n²) и O(n log n) алгоритмы',
                        status: 'not-passed',
                        tags: ['sorting'],
                        difficulty: 'hard',
                        durationInMinutes: 50,
                        xpReward: 100,
                        mdContent: '# Сортировка\n\nСравнение алгоритмов сортировки...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_007_3_2',
                        title: 'Бинарный поиск',
                        slug: 'binary-search',
                        description: 'Поиск в отсортированном массиве',
                        status: 'not-passed',
                        tags: ['search'],
                        difficulty: 'medium',
                        durationInMinutes: 30,
                        xpReward: 60,
                        mdContent: '# Бинарный поиск\n\nБинарный поиск работает за O(log n)...',
                        tasks: [
                            {
                                id: 'task_007_3_2_1',
                                variants: [
                                    { id: 'var1', title: 'O(log n)', isAnswer: true },
                                    { id: 'var2', title: 'O(n)', isAnswer: false },
                                ],
                            },
                        ],
                    },
                    {
                        id: 'lesson_007_3_3',
                        title: 'Динамическое программирование',
                        slug: 'dynamic-programming',
                        description: 'Мемоизация, табуляция, задачи',
                        status: 'not-passed',
                        tags: ['dp'],
                        difficulty: 'hard',
                        durationInMinutes: 65,
                        xpReward: 130,
                        mdContent: '# Динамическое программирование\n\nDP - оптимизация...',
                        tasks: [],
                    },
                ],
            },
        ],
    },
    {
        id: 'course_008',
        title: 'HTML/CSS: Мастерство верстки',
        status: 'popular',
        description:
            'Полный курс по современной верстке. Flexbox, Grid, адаптивный дизайн, анимации, препроцессоры и методологии CSS.',
        category: 'web-design',
        subCategory: 'frontend',
        tags: ['html', 'css', 'flexbox', 'grid', 'responsive', 'scss'],
        icon: '🎨',
        difficulty: 'beginner',
        xpReward: 400,
        estimatedHours: 3,
        userMeta: {
            startCourse: true,
            currentLesson: 3,
        },
        modules: [
            {
                id: 'module_008_1',
                title: 'Основы HTML',
                lessons: [
                    {
                        id: 'lesson_008_1_1',
                        title: 'Структура HTML документа',
                        slug: 'html-structure',
                        description: 'DOCTYPE, html, head, body, мета-теги',
                        status: 'active',
                        tags: ['html'],
                        difficulty: 'easy',
                        durationInMinutes: 20,
                        xpReward: 40,
                        mdContent: '# HTML\n\nHTML - язык разметки...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_008_1_2',
                        title: 'Семантическая верстка',
                        slug: 'semantic-html',
                        description: 'header, main, section, article, nav, footer',
                        status: 'not-passed',
                        tags: ['semantic'],
                        difficulty: 'easy',
                        durationInMinutes: 30,
                        xpReward: 60,
                        mdContent: '# Семантика\n\nСемантические теги улучшают SEO...',
                        tasks: [
                            {
                                id: 'task_008_1_2_1',
                                variants: [
                                    { id: 'var1', title: '<article>', isAnswer: true },
                                    { id: 'var2', title: '<div>', isAnswer: false },
                                ],
                            },
                        ],
                    },
                    {
                        id: 'lesson_008_1_3',
                        title: 'Формы и таблицы',
                        slug: 'forms-tables',
                        description: 'input, select, textarea, button, table',
                        status: 'not-passed',
                        tags: ['forms', 'tables'],
                        difficulty: 'easy',
                        durationInMinutes: 25,
                        xpReward: 50,
                        mdContent: '# Формы\n\nФормы для ввода данных...',
                        tasks: [],
                    },
                ],
            },
            {
                id: 'module_008_2',
                title: 'CSS: Стилизация',
                lessons: [
                    {
                        id: 'lesson_008_2_1',
                        title: 'Селекторы и свойства',
                        slug: 'css-selectors',
                        description: 'Классы, ID, псевдоклассы, псевдоэлементы',
                        status: 'not-passed',
                        tags: ['selectors'],
                        difficulty: 'easy',
                        durationInMinutes: 35,
                        xpReward: 70,
                        mdContent: '# CSS\n\nCSS для стилизации...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_008_2_2',
                        title: 'Flexbox',
                        slug: 'flexbox',
                        description: 'display: flex, justify-content, align-items, flex-direction',
                        status: 'not-passed',
                        tags: ['flexbox'],
                        difficulty: 'medium',
                        durationInMinutes: 45,
                        xpReward: 90,
                        mdContent: '# Flexbox\n\nFlexbox для одномерной верстки...',
                        tasks: [
                            {
                                id: 'task_008_2_2_1',
                                variants: [
                                    { id: 'var1', title: 'justify-content', isAnswer: true },
                                    { id: 'var2', title: 'align-content', isAnswer: false },
                                ],
                            },
                        ],
                    },
                    {
                        id: 'lesson_008_2_3',
                        title: 'CSS Grid',
                        slug: 'css-grid',
                        description: 'grid-template-columns, grid-template-rows, gap',
                        status: 'not-passed',
                        tags: ['grid'],
                        difficulty: 'medium',
                        durationInMinutes: 50,
                        xpReward: 100,
                        mdContent: '# CSS Grid\n\nGrid для двумерной верстки...',
                        tasks: [],
                    },
                ],
            },
            {
                id: 'module_008_3',
                title: 'Продвинутый CSS',
                lessons: [
                    {
                        id: 'lesson_008_3_1',
                        title: 'Адаптивный дизайн',
                        slug: 'responsive-design',
                        description: 'Media queries, mobile-first, viewport',
                        status: 'not-passed',
                        tags: ['responsive'],
                        difficulty: 'medium',
                        durationInMinutes: 40,
                        xpReward: 80,
                        mdContent: '# Адаптивность\n\nАдаптивный дизайн для разных экранов...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_008_3_2',
                        title: 'Анимации и transitions',
                        slug: 'animations',
                        description: 'transition, transform, @keyframes',
                        status: 'not-passed',
                        tags: ['animations'],
                        difficulty: 'medium',
                        durationInMinutes: 35,
                        xpReward: 70,
                        mdContent: '# Анимации\n\nАнимации оживляют интерфейс...',
                        tasks: [
                            {
                                id: 'task_008_3_2_1',
                                variants: [
                                    { id: 'var1', title: 'transition', isAnswer: true },
                                    { id: 'var2', title: 'transform', isAnswer: false },
                                ],
                            },
                        ],
                    },
                    {
                        id: 'lesson_008_3_3',
                        title: 'SCSS препроцессор',
                        slug: 'scss',
                        description: 'Переменные, вложенность, миксины',
                        status: 'not-passed',
                        tags: ['scss'],
                        difficulty: 'hard',
                        durationInMinutes: 40,
                        xpReward: 80,
                        mdContent: '# SCSS\n\nSCSS расширяет CSS возможностями...',
                        tasks: [],
                    },
                ],
            },
        ],
    },
    {
        id: 'course_009',
        title: 'Базы данных: SQL',
        status: null,
        description:
            'Изучите SQL от основ до продвинутых техник. Запросы, JOIN, подзапросы, индексы, оптимизация и проектирование БД.',
        category: 'programming',
        subCategory: 'database',
        tags: ['sql', 'database', 'postgresql', 'mysql', 'data'],
        icon: '🗄️',
        difficulty: 'intermediate',
        xpReward: 750,
        estimatedHours: 4,
        userMeta: {
            startCourse: false,
        },
        modules: [
            {
                id: 'module_009_1',
                title: 'Основы SQL',
                lessons: [
                    {
                        id: 'lesson_009_1_1',
                        title: 'SELECT и фильтрация',
                        slug: 'select-where',
                        description: 'SELECT, FROM, WHERE, ORDER BY',
                        status: 'not-passed',
                        tags: ['select', 'where'],
                        difficulty: 'easy',
                        durationInMinutes: 30,
                        xpReward: 60,
                        mdContent: '# SQL\n\nSQL - язык запросов...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_009_1_2',
                        title: 'Функции агрегации',
                        slug: 'aggregation',
                        description: 'COUNT, SUM, AVG, MIN, MAX, GROUP BY',
                        status: 'not-passed',
                        tags: ['aggregation'],
                        difficulty: 'medium',
                        durationInMinutes: 35,
                        xpReward: 70,
                        mdContent: '# Агрегация\n\nАгрегатные функции...',
                        tasks: [
                            {
                                id: 'task_009_1_2_1',
                                variants: [
                                    { id: 'var1', title: 'GROUP BY', isAnswer: true },
                                    { id: 'var2', title: 'ORDER BY', isAnswer: false },
                                ],
                            },
                        ],
                    },
                    {
                        id: 'lesson_009_1_3',
                        title: 'INSERT, UPDATE, DELETE',
                        slug: 'dml',
                        description: 'Добавление, обновление, удаление данных',
                        status: 'not-passed',
                        tags: ['dml'],
                        difficulty: 'easy',
                        durationInMinutes: 25,
                        xpReward: 50,
                        mdContent: '# DML\n\nМанипуляция данными...',
                        tasks: [],
                    },
                ],
            },
            {
                id: 'module_009_2',
                title: 'Связи и JOIN',
                lessons: [
                    {
                        id: 'lesson_009_2_1',
                        title: 'INNER JOIN и LEFT JOIN',
                        slug: 'joins',
                        description: 'Объединение таблиц',
                        status: 'not-passed',
                        tags: ['joins'],
                        difficulty: 'medium',
                        durationInMinutes: 45,
                        xpReward: 90,
                        mdContent: '# JOIN\n\nJOIN объединяет таблицы...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_009_2_2',
                        title: 'Подзапросы',
                        slug: 'subqueries',
                        description: 'Вложенные SELECT',
                        status: 'not-passed',
                        tags: ['subqueries'],
                        difficulty: 'hard',
                        durationInMinutes: 40,
                        xpReward: 80,
                        mdContent: '# Подзапросы\n\nПодзапросы внутри других запросов...',
                        tasks: [
                            {
                                id: 'task_009_2_2_1',
                                variants: [
                                    { id: 'var1', title: 'EXISTS', isAnswer: true },
                                    { id: 'var2', title: 'IN', isAnswer: false },
                                ],
                            },
                        ],
                    },
                    {
                        id: 'lesson_009_2_3',
                        title: 'Индексы и оптимизация',
                        slug: 'indexes',
                        description: 'CREATE INDEX, EXPLAIN, производительность',
                        status: 'not-passed',
                        tags: ['indexes'],
                        difficulty: 'hard',
                        durationInMinutes: 50,
                        xpReward: 100,
                        mdContent: '# Индексы\n\nИндексы ускоряют поиск...',
                        tasks: [],
                    },
                ],
            },
            {
                id: 'module_009_3',
                title: 'Проектирование БД',
                lessons: [
                    {
                        id: 'lesson_009_3_1',
                        title: 'Нормализация',
                        slug: 'normalization',
                        description: '1NF, 2NF, 3NF, BCNF',
                        status: 'not-passed',
                        tags: ['normalization'],
                        difficulty: 'hard',
                        durationInMinutes: 45,
                        xpReward: 90,
                        mdContent: '# Нормализация\n\nУстранение избыточности...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_009_3_2',
                        title: 'Транзакции и ACID',
                        slug: 'transactions',
                        description: 'BEGIN, COMMIT, ROLLBACK, изоляция',
                        status: 'not-passed',
                        tags: ['transactions'],
                        difficulty: 'hard',
                        durationInMinutes: 40,
                        xpReward: 80,
                        mdContent: '# Транзакции\n\nГруппировка операций...',
                        tasks: [
                            {
                                id: 'task_009_3_2_1',
                                variants: [
                                    { id: 'var1', title: 'ACID', isAnswer: true },
                                    { id: 'var2', title: 'BASE', isAnswer: false },
                                ],
                            },
                        ],
                    },
                ],
            },
        ],
    },
    {
        id: 'course_010',
        title: 'Git: Контроль версий',
        status: 'hot',
        description:
            'Освойте Git для эффективной командной работы. Ветвление, слияние, разрешение конфликтов, Git Flow и CI/CD.',
        category: 'devops',
        subCategory: 'version-control',
        tags: ['git', 'github', 'version-control', 'devops', 'teamwork'],
        icon: '📝',
        difficulty: 'beginner',
        xpReward: 350,
        estimatedHours: 2.5,
        userMeta: {
            startCourse: true,
            currentLesson: 2,
            currentModule: 1,
        },
        modules: [
            {
                id: 'module_010_1',
                title: 'Основы Git',
                lessons: [
                    {
                        id: 'lesson_010_1_1',
                        title: 'Установка и настройка',
                        slug: 'git-setup',
                        description: 'git config, git init, git clone',
                        status: 'active',
                        tags: ['setup'],
                        difficulty: 'easy',
                        durationInMinutes: 20,
                        xpReward: 40,
                        mdContent: '# Git\n\nGit - система контроля версий...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_010_1_2',
                        title: 'Базовые команды',
                        slug: 'basic-commands',
                        description: 'git add, git commit, git status, git log',
                        status: 'not-passed',
                        tags: ['basics'],
                        difficulty: 'easy',
                        durationInMinutes: 30,
                        xpReward: 60,
                        mdContent: '# Базовые команды\n\nОсновные операции с репозиторием...',
                        tasks: [
                            {
                                id: 'task_010_1_2_1',
                                variants: [
                                    { id: 'var1', title: 'git commit -m', isAnswer: true },
                                    { id: 'var2', title: 'git save', isAnswer: false },
                                ],
                            },
                        ],
                    },
                    {
                        id: 'lesson_010_1_3',
                        title: 'Просмотр истории и изменений',
                        slug: 'history-diff',
                        description: 'git log, git diff, git show',
                        status: 'not-passed',
                        tags: ['history'],
                        difficulty: 'easy',
                        durationInMinutes: 25,
                        xpReward: 50,
                        mdContent: '# История\n\nПросмотр изменений...',
                        tasks: [],
                    },
                ],
            },
            {
                id: 'module_010_2',
                title: 'Ветвление и слияние',
                lessons: [
                    {
                        id: 'lesson_010_2_1',
                        title: 'Создание и переключение веток',
                        slug: 'branches',
                        description: 'git branch, git checkout, git switch',
                        status: 'not-passed',
                        tags: ['branches'],
                        difficulty: 'medium',
                        durationInMinutes: 35,
                        xpReward: 70,
                        mdContent: '# Ветвление\n\nВетки для параллельной разработки...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_010_2_2',
                        title: 'Слияние веток',
                        slug: 'merging',
                        description: 'git merge, fast-forward, трехстороннее слияние',
                        status: 'not-passed',
                        tags: ['merge'],
                        difficulty: 'medium',
                        durationInMinutes: 40,
                        xpReward: 80,
                        mdContent: '# Слияние\n\nОбъединение изменений...',
                        tasks: [
                            {
                                id: 'task_010_2_2_1',
                                variants: [
                                    { id: 'var1', title: 'git merge', isAnswer: true },
                                    { id: 'var2', title: 'git rebase', isAnswer: false },
                                ],
                            },
                        ],
                    },
                    {
                        id: 'lesson_010_2_3',
                        title: 'Разрешение конфликтов',
                        slug: 'conflicts',
                        description: 'Конфликты при merge, ручное разрешение',
                        status: 'not-passed',
                        tags: ['conflicts'],
                        difficulty: 'hard',
                        durationInMinutes: 45,
                        xpReward: 90,
                        mdContent:
                            '# Конфликты\n\nКонфликты возникают при изменении одних и тех же строк...',
                        tasks: [],
                    },
                ],
            },
            {
                id: 'module_010_3',
                title: 'Git Flow и GitHub',
                lessons: [
                    {
                        id: 'lesson_010_3_1',
                        title: 'Удаленные репозитории',
                        slug: 'remote',
                        description: 'git remote, git push, git pull, git fetch',
                        status: 'not-passed',
                        tags: ['remote'],
                        difficulty: 'medium',
                        durationInMinutes: 35,
                        xpReward: 70,
                        mdContent: '# Удаленные репозитории\n\nСинхронизация с GitHub/GitLab...',
                        tasks: [],
                    },
                    {
                        id: 'lesson_010_3_2',
                        title: 'Pull Requests',
                        slug: 'pull-requests',
                        description: 'Создание PR, ревью, CI/CD',
                        status: 'not-passed',
                        tags: ['pr', 'github'],
                        difficulty: 'hard',
                        durationInMinutes: 40,
                        xpReward: 80,
                        mdContent: '# Pull Requests\n\nPR для code review...',
                        tasks: [
                            {
                                id: 'task_010_3_2_1',
                                variants: [
                                    { id: 'var1', title: 'Pull Request', isAnswer: true },
                                    { id: 'var2', title: 'Push Request', isAnswer: false },
                                ],
                            },
                        ],
                    },
                    {
                        id: 'lesson_010_3_3',
                        title: 'Git Flow стратегия',
                        slug: 'git-flow',
                        description: 'main, develop, feature, release, hotfix ветки',
                        status: 'not-passed',
                        tags: ['git-flow'],
                        difficulty: 'hard',
                        durationInMinutes: 45,
                        xpReward: 90,
                        mdContent: '# Git Flow\n\nПопулярная модель ветвления...',
                        tasks: [],
                    },
                ],
            },
        ],
    },
];

const COURSE_FOR_TEST: Course = {
    id: 'course_002',
    title: 'TypeScript: Полное руководство',
    status: null,
    description:
        'Изучите TypeScript с нуля до продвинутого уровня. Типизация, интерфейсы, generics, утилитарные типы и интеграция с React.',
    category: 'programming',
    subCategory: 'frontend',
    tags: ['typescript', 'javascript', 'frontend', 'hard'],
    icon: '📘',
    difficulty: 'intermediate',
    xpReward: 800,
    estimatedHours: 2.5,
    userMeta: {
        startCourse: true,
        currentLesson: 1,
        currentModule: 2,
    },
    modules: [
        {
            id: 'module_002_1',
            title: 'Основы TypeScript',
            lessons: [
                {
                    id: 'lesson_002_1_1',
                    title: 'Введение в TypeScript',
                    slug: 'intro-to-typescript',
                    description: 'Что такое TypeScript, установка, настройка tsconfig.json',
                    status: 'active',
                    tags: ['intro', 'setup'],
                    difficulty: 'easy',
                    durationInMinutes: 30,
                    xpReward: 60,
                    mdContent: '# TypeScript\n\nTypeScript - это надмножество JavaScript...',
                    tasks: [],
                },
                {
                    id: 'lesson_002_1_2',
                    title: 'Базовые типы',
                    slug: 'basic-types',
                    description: 'string, number, boolean, array, tuple, enum',
                    status: 'not-passed',
                    tags: ['types', 'basics'],
                    difficulty: 'easy',
                    durationInMinutes: 35,
                    xpReward: 70,
                    mdContent:
                        '# Базовые типы\n\nTypeScript предоставляет богатую систему типов...',
                    tasks: [
                        {
                            id: 'task_002_1_2_1',
                            variants: [
                                { id: 'var1', title: 'tuple', isAnswer: true },
                                { id: 'var2', title: 'object', isAnswer: false },
                            ],
                        },
                    ],
                },
                {
                    id: 'lesson_002_1_3',
                    title: 'Union и Intersection типы',
                    slug: 'union-intersection',
                    description: 'Объединение и пересечение типов, type aliases',
                    status: 'not-passed',
                    tags: ['union', 'intersection'],
                    difficulty: 'medium',
                    durationInMinutes: 40,
                    xpReward: 80,
                    mdContent: '# Union и Intersection\n\nUnion типы позволяют переменной...',
                    tasks: [],
                },
            ],
        },
        {
            id: 'module_002_2',
            title: 'Продвинутая типизация',
            lessons: [
                {
                    id: 'lesson_002_2_1',
                    title: 'Интерфейсы',
                    slug: 'interfaces',
                    description: 'Создание интерфейсов, опциональные свойства, readonly',
                    status: 'not-passed',
                    tags: ['interfaces'],
                    difficulty: 'medium',
                    durationInMinutes: 35,
                    xpReward: 70,
                    mdContent: '# Интерфейсы\n\nИнтерфейсы описывают форму объекта...',
                    tasks: [],
                },
                {
                    id: 'lesson_002_2_2',
                    title: 'Generics',
                    slug: 'generics',
                    description: 'Обобщенные типы, ограничения, generic функции и классы',
                    status: 'not-passed',
                    tags: ['generics'],
                    difficulty: 'hard',
                    durationInMinutes: 50,
                    xpReward: 100,
                    mdContent: '# Generics\n\nGenerics позволяют создавать компоненты...',
                    tasks: [
                        {
                            id: 'task_002_2_2_1',
                            variants: [
                                { id: 'var1', title: '<T>', isAnswer: true },
                                { id: 'var2', title: 'any', isAnswer: false },
                            ],
                        },
                    ],
                },
                {
                    id: 'lesson_002_2_3',
                    title: 'Утилитарные типы',
                    slug: 'utility-types',
                    description: 'Partial, Required, Readonly, Pick, Omit, Record',
                    status: 'not-passed',
                    tags: ['utility-types'],
                    difficulty: 'hard',
                    durationInMinutes: 45,
                    xpReward: 90,
                    mdContent: '# Утилитарные типы\n\nTypeScript предоставляет встроенные...',
                    tasks: [],
                },
            ],
        },
        {
            id: 'module_002_3',
            title: 'TypeScript в React',
            lessons: [
                {
                    id: 'lesson_002_3_1',
                    title: 'Типизация компонентов React',
                    slug: 'react-components-typing',
                    description: 'FC, PropsWithChildren, типизация пропсов',
                    status: 'not-passed',
                    tags: ['react', 'components'],
                    difficulty: 'hard',
                    durationInMinutes: 40,
                    xpReward: 80,
                    mdContent: '# React + TypeScript\n\nТипизация React компонентов...',
                    tasks: [],
                },
                {
                    id: 'lesson_002_3_2',
                    title: 'Хуки с TypeScript',
                    slug: 'hooks-with-typescript',
                    description: 'useState, useEffect, useReducer, useContext с типами',
                    status: 'not-passed',
                    tags: ['hooks', 'react'],
                    difficulty: 'hard',
                    durationInMinutes: 45,
                    xpReward: 90,
                    mdContent: '# Типизация хуков\n\nКаждый React хук можно типизировать...',
                    tasks: [
                        {
                            id: 'task_002_3_2_1',
                            variants: [
                                { id: 'var1', title: 'useState<number>', isAnswer: true },
                                { id: 'var2', title: 'useState()', isAnswer: false },
                            ],
                        },
                    ],
                },
            ],
        },
    ],
};

const CATEGORIES_TEST: Category[] = [
    { id: '1', title: 'Frontend', challengesCount: 10 },
    { id: '2', title: 'Backend', challengesCount: 14 },
    { id: '3', title: 'AI / ML', challengesCount: 26 },
    { id: '4', title: 'DevOps', challengesCount: 38 },
    { id: '5', title: 'Алгоритмы', challengesCount: 125 },
];

const LANGUAGE_TEST: Language[] = [
    { id: '1', title: 'JavaScript', challengesCount: 10 },
    { id: '2', title: 'Python', challengesCount: 14 },
    { id: '3', title: 'Rust', challengesCount: 26 },
    { id: '4', title: 'Go', challengesCount: 38 },
    { id: '5', title: 'C++', challengesCount: 125 },
];

export type Filters = {
    categories?: string[];
    difficulty?: 'easy' | 'medium' | 'hard';
    languages?: string[];
    sortBy?: string;
    duration?: string;
    inProgress?: boolean;
};

export const coursesApi = {
    getCourses: async (_: Filters = {}) => {
        return Promise.resolve(COURSES_FOR_TEST);
    },

    getCourse: async (_id: string) => {
        return Promise.resolve(COURSE_FOR_TEST);
    },

    getUserCourses: async () => {
        return Promise.resolve(COURSES_FOR_TEST);
    },

    getCoursesCategories: async () => {
        return Promise.resolve(CATEGORIES_TEST);
    },

    getCoursesLanguages: async () => {
        return Promise.resolve(LANGUAGE_TEST);
    },
};
